### ISSUE TITLE
Failed to activate the plist-converter package

### ISSUE THREAD

**Issue by wao1201** [danielbayley/atom-plist-converter#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [plist-converter](https://github.com/danielbayley/atom-plist-converter) package, v0.1.2
### Stack Trace

Failed to activate the plist-converter package

```
At Command failed: plutil -convert xml1 -o - '/Applications/YAAW.app/Contents/Info.plist'


Error: Command failed: plutil -convert xml1 -o - '/Applications/YAAW.app/Contents/Info.plist'

    at checkExecSyncError (child_process.js:453:13)
    at execSync (child_process.js:493:13)
    at /Users/wao1201/.atom/packages/plist-converter/index.coffee:11:13
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at Object.module.exports.activate (/Users/wao1201/.atom/packages/plist-converter/index.coffee:4:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:85:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/wao1201/Documents/Dev",
    "themes": [
      "native-ui",
      "slime"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.14
file-icons, v1.6.13
linter, v1.11.3
minimap, v4.18.0
native-ui, v0.10.0
pigments, v0.19.3
plist-converter, v0.1.2
project-manager, v2.6.5
slime, v1.4.0
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by danielbayley** [comment]
@wao1201 The [latest update](https://github.com/danielbayley/atom-plist-converter/releases/tag/v0.1.3) should fix anything like this.
